### ISSUE TITLE
Can it strip utf8-bom ?

### ISSUE THREAD

**Issue by Samlv9** [rogeriopvl/gulp-mustache#17]
1, this plugin does not strip utf8 bom when using `{{>part}}`.
2, `{{>part}}` only suport `.mustache` extesion, if i have a part named `part.html`, this plugin will get an error.
3, at `index.js` (`line:46`, `line:62`) the function `loadPartials()`'s `this` context is undefined.

``` javascript
/// index.js, line: 46 and line: 76
loadPartials(template, file.path);

/// when `{{>part}}` file no found call `this.emit()` will get an error:
this.emit('error', new gutil.PluginError('gulp-mustache', "Unable to load partial file: " + partialPath));

/// I think this will fixed `this` is undefined bug. 
loadPartials.call(this, template, file.path);
```

**Comment by kribblo** [comment]
1. Pretty crazy that this is still an issue, haven't seen that since ~ 2000-2002 :) Which editor?
2. Would probably be reasonable to try to fall back to the filename without added .mustache if the first does not exist
3. Your commit seems reasonable there

**Comment by Samlv9** [comment]
@kribblo I am use `Visual Studio 2015`

**Comment by rogeriopvl** [comment]
Hi @Samlv9, care to make a PR with those changes?

**Comment by Samlv9** [comment]
sorry, i does not use github very, but i have make one~ 
#19

**Comment by rogeriopvl** [comment]
@Samlv9 thanks for the PR. I just have a question regarding stripbom: couldn't this be solved outside of `gulp-mustache` with [gulp-stripbom](https://github.com/lichunqiang/gulp-stripbom) ?

I'm concerned that `gulp-mustache` should not be doing this because it kinda falls outside of it's scope.

I would like to hear your thoughts and @kribblo 's on this.

**Comment by Samlv9** [comment]
I don't think that is necessary. Because all of the `partials` file only required by `gulp-mustache` but not other `gulp-plugins`, In fact, Gulp pipe line even does not know their exists.

If we wanna move `strip-bom` outside of `gulp-mustache`, How about create another plugin to do `loadPartials()`'s job? after that pass its result to `gulp-mustache` as `partials` argument.

But it look like too complicated, So I think, its simple and better to do:
```javascript
var partial = stripbom(fs.readFileSync(partialPath, 'utf8'));
```

**Comment by kribblo** [comment]
@rogeriopvl @Samlv9 yeah that doesn't belong in this plugin. You can use another task instead that runs before your mustache task, it doesn't have to pipe.

I would even say that this is a very unusual use case in 2015. I also think it might be solved by simply serving UTF-8:

```html
<meta charset="utf-8"> 
```

Otherwise configure your editor to save without BOM instead. [BOM for UTF-8 does not make any sense](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8).

**Comment by rogeriopvl** [comment]
@Samlv9 I really like that idea of `loadPartials()` being a different plugin. Thats something that's been bugging me since ever. I'm going to investigate a bit further to see what it takes to do that ;)

**Comment by Samlv9** [comment]
okay, got it!

**Comment by Samlv9** [comment]
I have an other idea about remove utf8-bom,  how about use `trim()` instead of `strip-bom`? so we does not need other plugin any more...

**Comment by rogeriopvl** [comment]
@Samlv9 the issue here is not having another plugin, it's just making sure that `gulp-mustache` follows the single responsibility principle. I think that it should be the user's responsibility to make sure files are passed "clean" to `gulp-mustache`.

**Comment by Samlv9** [comment]
yeah, you are right. i means for right now solution……:joy:
